baseURL = "https://noamelf.com"
languageCode = "en-us"
title = "noamelf"
theme = "hugo-kiera"

pygmentsCodeFences = true
googleAnalytics = "UA-62273869-1" #Google Analytics ID

[author]
    name = "Noam Elfanbaum"           #Author name
    github = "noamelf"         #Github username
    linkedin = "noamelf"       #LinkedIn username
    twitter = "noamelf"        #Twitter username

[params]
    tagline = "thoughts about software development and more"
