baseURL: https://noamelf.com
enableInlineShortcodes: true
googleAnalytics: G-GZL41FLBX8
ignoreLogs: [warning-goldmark-raw-html]
languageCode: en
markup:
  highlight:
    noClasses: false
menu:
  main:
    - name: About
      url: about/
      weight: 10
    - name: Projects
      url: projects/
      weight: 30
    - name: Talks
      url: talks/
      weight: 40
params:
  author: Me
  defaultTheme: auto 
  description: Thoughts on software development and more!
  env: development
  homeInfoParams:
    Title: Hi there 👋
    Content: Welcome to my blog where I write my thoughts on software development, management and more!
  showCodeCopyButtons: true
  socialIcons:
    - name: github
      url: https://github.com/noamelf
    - name: linkedin
      url: https://www.linkedin.com/in/noamelf/
    - name: x
      url: https://twitter.com/noamelf
  title: noamelf
pygmentsUseClasses: true
theme: PaperMod
title: noamelf
